/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-08 at 00:40:16 UTC 
 * Modify at your own risk.
 */

package edu.columbia.cloud.plnr.entities.studygroupendpoint;

/**
 * Service definition for Studygroupendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StudygroupendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Studygroupendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the studygroupendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "studygroupendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Studygroupendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Studygroupendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getStudyGroup".
   *
   * This request holds the parameters needed by the the studygroupendpoint server.  After setting any
   * optional parameters, call the {@link GetStudyGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetStudyGroup getStudyGroup(java.lang.Long id) throws java.io.IOException {
    GetStudyGroup result = new GetStudyGroup(id);
    initialize(result);
    return result;
  }

  public class GetStudyGroup extends StudygroupendpointRequest<edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup> {

    private static final String REST_PATH = "studygroup/{id}";

    /**
     * Create a request for the method "getStudyGroup".
     *
     * This request holds the parameters needed by the the studygroupendpoint server.  After setting
     * any optional parameters, call the {@link GetStudyGroup#execute()} method to invoke the remote
     * operation. <p> {@link GetStudyGroup#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetStudyGroup(java.lang.Long id) {
      super(Studygroupendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetStudyGroup setAlt(java.lang.String alt) {
      return (GetStudyGroup) super.setAlt(alt);
    }

    @Override
    public GetStudyGroup setFields(java.lang.String fields) {
      return (GetStudyGroup) super.setFields(fields);
    }

    @Override
    public GetStudyGroup setKey(java.lang.String key) {
      return (GetStudyGroup) super.setKey(key);
    }

    @Override
    public GetStudyGroup setOauthToken(java.lang.String oauthToken) {
      return (GetStudyGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public GetStudyGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetStudyGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetStudyGroup setQuotaUser(java.lang.String quotaUser) {
      return (GetStudyGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetStudyGroup setUserIp(java.lang.String userIp) {
      return (GetStudyGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetStudyGroup setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetStudyGroup set(String parameterName, Object value) {
      return (GetStudyGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertStudyGroup".
   *
   * This request holds the parameters needed by the the studygroupendpoint server.  After setting any
   * optional parameters, call the {@link InsertStudyGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup}
   * @return the request
   */
  public InsertStudyGroup insertStudyGroup(edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup content) throws java.io.IOException {
    InsertStudyGroup result = new InsertStudyGroup(content);
    initialize(result);
    return result;
  }

  public class InsertStudyGroup extends StudygroupendpointRequest<edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup> {

    private static final String REST_PATH = "studygroup";

    /**
     * Create a request for the method "insertStudyGroup".
     *
     * This request holds the parameters needed by the the studygroupendpoint server.  After setting
     * any optional parameters, call the {@link InsertStudyGroup#execute()} method to invoke the
     * remote operation. <p> {@link InsertStudyGroup#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup}
     * @since 1.13
     */
    protected InsertStudyGroup(edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup content) {
      super(Studygroupendpoint.this, "POST", REST_PATH, content, edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup.class);
    }

    @Override
    public InsertStudyGroup setAlt(java.lang.String alt) {
      return (InsertStudyGroup) super.setAlt(alt);
    }

    @Override
    public InsertStudyGroup setFields(java.lang.String fields) {
      return (InsertStudyGroup) super.setFields(fields);
    }

    @Override
    public InsertStudyGroup setKey(java.lang.String key) {
      return (InsertStudyGroup) super.setKey(key);
    }

    @Override
    public InsertStudyGroup setOauthToken(java.lang.String oauthToken) {
      return (InsertStudyGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertStudyGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertStudyGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertStudyGroup setQuotaUser(java.lang.String quotaUser) {
      return (InsertStudyGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertStudyGroup setUserIp(java.lang.String userIp) {
      return (InsertStudyGroup) super.setUserIp(userIp);
    }

    @Override
    public InsertStudyGroup set(String parameterName, Object value) {
      return (InsertStudyGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listStudyGroup".
   *
   * This request holds the parameters needed by the the studygroupendpoint server.  After setting any
   * optional parameters, call the {@link ListStudyGroup#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListStudyGroup listStudyGroup() throws java.io.IOException {
    ListStudyGroup result = new ListStudyGroup();
    initialize(result);
    return result;
  }

  public class ListStudyGroup extends StudygroupendpointRequest<edu.columbia.cloud.plnr.entities.studygroupendpoint.model.CollectionResponseStudyGroup> {

    private static final String REST_PATH = "studygroup";

    /**
     * Create a request for the method "listStudyGroup".
     *
     * This request holds the parameters needed by the the studygroupendpoint server.  After setting
     * any optional parameters, call the {@link ListStudyGroup#execute()} method to invoke the remote
     * operation. <p> {@link ListStudyGroup#initialize(com.google.api.client.googleapis.services.Abstr
     * actGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @since 1.13
     */
    protected ListStudyGroup() {
      super(Studygroupendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.studygroupendpoint.model.CollectionResponseStudyGroup.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListStudyGroup setAlt(java.lang.String alt) {
      return (ListStudyGroup) super.setAlt(alt);
    }

    @Override
    public ListStudyGroup setFields(java.lang.String fields) {
      return (ListStudyGroup) super.setFields(fields);
    }

    @Override
    public ListStudyGroup setKey(java.lang.String key) {
      return (ListStudyGroup) super.setKey(key);
    }

    @Override
    public ListStudyGroup setOauthToken(java.lang.String oauthToken) {
      return (ListStudyGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public ListStudyGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListStudyGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListStudyGroup setQuotaUser(java.lang.String quotaUser) {
      return (ListStudyGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListStudyGroup setUserIp(java.lang.String userIp) {
      return (ListStudyGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListStudyGroup setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListStudyGroup setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListStudyGroup set(String parameterName, Object value) {
      return (ListStudyGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeStudyGroup".
   *
   * This request holds the parameters needed by the the studygroupendpoint server.  After setting any
   * optional parameters, call the {@link RemoveStudyGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveStudyGroup removeStudyGroup(java.lang.Long id) throws java.io.IOException {
    RemoveStudyGroup result = new RemoveStudyGroup(id);
    initialize(result);
    return result;
  }

  public class RemoveStudyGroup extends StudygroupendpointRequest<Void> {

    private static final String REST_PATH = "studygroup/{id}";

    /**
     * Create a request for the method "removeStudyGroup".
     *
     * This request holds the parameters needed by the the studygroupendpoint server.  After setting
     * any optional parameters, call the {@link RemoveStudyGroup#execute()} method to invoke the
     * remote operation. <p> {@link RemoveStudyGroup#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveStudyGroup(java.lang.Long id) {
      super(Studygroupendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveStudyGroup setAlt(java.lang.String alt) {
      return (RemoveStudyGroup) super.setAlt(alt);
    }

    @Override
    public RemoveStudyGroup setFields(java.lang.String fields) {
      return (RemoveStudyGroup) super.setFields(fields);
    }

    @Override
    public RemoveStudyGroup setKey(java.lang.String key) {
      return (RemoveStudyGroup) super.setKey(key);
    }

    @Override
    public RemoveStudyGroup setOauthToken(java.lang.String oauthToken) {
      return (RemoveStudyGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveStudyGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveStudyGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveStudyGroup setQuotaUser(java.lang.String quotaUser) {
      return (RemoveStudyGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveStudyGroup setUserIp(java.lang.String userIp) {
      return (RemoveStudyGroup) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveStudyGroup setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveStudyGroup set(String parameterName, Object value) {
      return (RemoveStudyGroup) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStudyGroup".
   *
   * This request holds the parameters needed by the the studygroupendpoint server.  After setting any
   * optional parameters, call the {@link UpdateStudyGroup#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup}
   * @return the request
   */
  public UpdateStudyGroup updateStudyGroup(edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup content) throws java.io.IOException {
    UpdateStudyGroup result = new UpdateStudyGroup(content);
    initialize(result);
    return result;
  }

  public class UpdateStudyGroup extends StudygroupendpointRequest<edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup> {

    private static final String REST_PATH = "studygroup";

    /**
     * Create a request for the method "updateStudyGroup".
     *
     * This request holds the parameters needed by the the studygroupendpoint server.  After setting
     * any optional parameters, call the {@link UpdateStudyGroup#execute()} method to invoke the
     * remote operation. <p> {@link UpdateStudyGroup#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup}
     * @since 1.13
     */
    protected UpdateStudyGroup(edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup content) {
      super(Studygroupendpoint.this, "PUT", REST_PATH, content, edu.columbia.cloud.plnr.entities.studygroupendpoint.model.StudyGroup.class);
    }

    @Override
    public UpdateStudyGroup setAlt(java.lang.String alt) {
      return (UpdateStudyGroup) super.setAlt(alt);
    }

    @Override
    public UpdateStudyGroup setFields(java.lang.String fields) {
      return (UpdateStudyGroup) super.setFields(fields);
    }

    @Override
    public UpdateStudyGroup setKey(java.lang.String key) {
      return (UpdateStudyGroup) super.setKey(key);
    }

    @Override
    public UpdateStudyGroup setOauthToken(java.lang.String oauthToken) {
      return (UpdateStudyGroup) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStudyGroup setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStudyGroup) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStudyGroup setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStudyGroup) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStudyGroup setUserIp(java.lang.String userIp) {
      return (UpdateStudyGroup) super.setUserIp(userIp);
    }

    @Override
    public UpdateStudyGroup set(String parameterName, Object value) {
      return (UpdateStudyGroup) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Studygroupendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Studygroupendpoint}. */
    @Override
    public Studygroupendpoint build() {
      return new Studygroupendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StudygroupendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStudygroupendpointRequestInitializer(
        StudygroupendpointRequestInitializer studygroupendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(studygroupendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
