/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-08 at 00:40:29 UTC 
 * Modify at your own risk.
 */

package edu.columbia.cloud.plnr.entities.requestreplyendpoint.model;

/**
 * Model definition for RequestReply.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the requestreplyendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class RequestReply extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Boolean accept;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Key key;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private Subject subject;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private User target;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Boolean getAccept() {
    return accept;
  }

  /**
   * @param accept accept or {@code null} for none
   */
  public RequestReply setAccept(java.lang.Boolean accept) {
    this.accept = accept;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Key getKey() {
    return key;
  }

  /**
   * @param key key or {@code null} for none
   */
  public RequestReply setKey(Key key) {
    this.key = key;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public Subject getSubject() {
    return subject;
  }

  /**
   * @param subject subject or {@code null} for none
   */
  public RequestReply setSubject(Subject subject) {
    this.subject = subject;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public User getTarget() {
    return target;
  }

  /**
   * @param target target or {@code null} for none
   */
  public RequestReply setTarget(User target) {
    this.target = target;
    return this;
  }

  @Override
  public RequestReply set(String fieldName, Object value) {
    return (RequestReply) super.set(fieldName, value);
  }

  @Override
  public RequestReply clone() {
    return (RequestReply) super.clone();
  }

}
