/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-08 at 00:40:29 UTC 
 * Modify at your own risk.
 */

package edu.columbia.cloud.plnr.entities.requestreplyendpoint;

/**
 * Service definition for Requestreplyendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RequestreplyendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Requestreplyendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the requestreplyendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "requestreplyendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Requestreplyendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Requestreplyendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRequestReply".
   *
   * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
   * any optional parameters, call the {@link GetRequestReply#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetRequestReply getRequestReply(java.lang.Long id) throws java.io.IOException {
    GetRequestReply result = new GetRequestReply(id);
    initialize(result);
    return result;
  }

  public class GetRequestReply extends RequestreplyendpointRequest<edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply> {

    private static final String REST_PATH = "requestreply/{id}";

    /**
     * Create a request for the method "getRequestReply".
     *
     * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
     * any optional parameters, call the {@link GetRequestReply#execute()} method to invoke the remote
     * operation. <p> {@link GetRequestReply#initialize(com.google.api.client.googleapis.services.Abst
     * ractGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRequestReply(java.lang.Long id) {
      super(Requestreplyendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRequestReply setAlt(java.lang.String alt) {
      return (GetRequestReply) super.setAlt(alt);
    }

    @Override
    public GetRequestReply setFields(java.lang.String fields) {
      return (GetRequestReply) super.setFields(fields);
    }

    @Override
    public GetRequestReply setKey(java.lang.String key) {
      return (GetRequestReply) super.setKey(key);
    }

    @Override
    public GetRequestReply setOauthToken(java.lang.String oauthToken) {
      return (GetRequestReply) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRequestReply setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRequestReply) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRequestReply setQuotaUser(java.lang.String quotaUser) {
      return (GetRequestReply) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRequestReply setUserIp(java.lang.String userIp) {
      return (GetRequestReply) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRequestReply setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRequestReply set(String parameterName, Object value) {
      return (GetRequestReply) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRequestReply".
   *
   * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
   * any optional parameters, call the {@link InsertRequestReply#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply}
   * @return the request
   */
  public InsertRequestReply insertRequestReply(edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply content) throws java.io.IOException {
    InsertRequestReply result = new InsertRequestReply(content);
    initialize(result);
    return result;
  }

  public class InsertRequestReply extends RequestreplyendpointRequest<edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply> {

    private static final String REST_PATH = "requestreply";

    /**
     * Create a request for the method "insertRequestReply".
     *
     * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
     * any optional parameters, call the {@link InsertRequestReply#execute()} method to invoke the
     * remote operation. <p> {@link InsertRequestReply#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply}
     * @since 1.13
     */
    protected InsertRequestReply(edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply content) {
      super(Requestreplyendpoint.this, "POST", REST_PATH, content, edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply.class);
    }

    @Override
    public InsertRequestReply setAlt(java.lang.String alt) {
      return (InsertRequestReply) super.setAlt(alt);
    }

    @Override
    public InsertRequestReply setFields(java.lang.String fields) {
      return (InsertRequestReply) super.setFields(fields);
    }

    @Override
    public InsertRequestReply setKey(java.lang.String key) {
      return (InsertRequestReply) super.setKey(key);
    }

    @Override
    public InsertRequestReply setOauthToken(java.lang.String oauthToken) {
      return (InsertRequestReply) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRequestReply setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRequestReply) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRequestReply setQuotaUser(java.lang.String quotaUser) {
      return (InsertRequestReply) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRequestReply setUserIp(java.lang.String userIp) {
      return (InsertRequestReply) super.setUserIp(userIp);
    }

    @Override
    public InsertRequestReply set(String parameterName, Object value) {
      return (InsertRequestReply) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRequestReply".
   *
   * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
   * any optional parameters, call the {@link ListRequestReply#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRequestReply listRequestReply() throws java.io.IOException {
    ListRequestReply result = new ListRequestReply();
    initialize(result);
    return result;
  }

  public class ListRequestReply extends RequestreplyendpointRequest<edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.CollectionResponseRequestReply> {

    private static final String REST_PATH = "requestreply";

    /**
     * Create a request for the method "listRequestReply".
     *
     * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
     * any optional parameters, call the {@link ListRequestReply#execute()} method to invoke the
     * remote operation. <p> {@link ListRequestReply#initialize(com.google.api.client.googleapis.servi
     * ces.AbstractGoogleClientRequest)} must be called to initialize this instance immediately after
     * invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRequestReply() {
      super(Requestreplyendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.CollectionResponseRequestReply.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRequestReply setAlt(java.lang.String alt) {
      return (ListRequestReply) super.setAlt(alt);
    }

    @Override
    public ListRequestReply setFields(java.lang.String fields) {
      return (ListRequestReply) super.setFields(fields);
    }

    @Override
    public ListRequestReply setKey(java.lang.String key) {
      return (ListRequestReply) super.setKey(key);
    }

    @Override
    public ListRequestReply setOauthToken(java.lang.String oauthToken) {
      return (ListRequestReply) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRequestReply setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRequestReply) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRequestReply setQuotaUser(java.lang.String quotaUser) {
      return (ListRequestReply) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRequestReply setUserIp(java.lang.String userIp) {
      return (ListRequestReply) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRequestReply setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRequestReply setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRequestReply set(String parameterName, Object value) {
      return (ListRequestReply) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRequestReply".
   *
   * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
   * any optional parameters, call the {@link RemoveRequestReply#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRequestReply removeRequestReply(java.lang.Long id) throws java.io.IOException {
    RemoveRequestReply result = new RemoveRequestReply(id);
    initialize(result);
    return result;
  }

  public class RemoveRequestReply extends RequestreplyendpointRequest<Void> {

    private static final String REST_PATH = "requestreply/{id}";

    /**
     * Create a request for the method "removeRequestReply".
     *
     * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
     * any optional parameters, call the {@link RemoveRequestReply#execute()} method to invoke the
     * remote operation. <p> {@link RemoveRequestReply#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRequestReply(java.lang.Long id) {
      super(Requestreplyendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRequestReply setAlt(java.lang.String alt) {
      return (RemoveRequestReply) super.setAlt(alt);
    }

    @Override
    public RemoveRequestReply setFields(java.lang.String fields) {
      return (RemoveRequestReply) super.setFields(fields);
    }

    @Override
    public RemoveRequestReply setKey(java.lang.String key) {
      return (RemoveRequestReply) super.setKey(key);
    }

    @Override
    public RemoveRequestReply setOauthToken(java.lang.String oauthToken) {
      return (RemoveRequestReply) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRequestReply setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRequestReply) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRequestReply setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRequestReply) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRequestReply setUserIp(java.lang.String userIp) {
      return (RemoveRequestReply) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRequestReply setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRequestReply set(String parameterName, Object value) {
      return (RemoveRequestReply) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRequestReply".
   *
   * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
   * any optional parameters, call the {@link UpdateRequestReply#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply}
   * @return the request
   */
  public UpdateRequestReply updateRequestReply(edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply content) throws java.io.IOException {
    UpdateRequestReply result = new UpdateRequestReply(content);
    initialize(result);
    return result;
  }

  public class UpdateRequestReply extends RequestreplyendpointRequest<edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply> {

    private static final String REST_PATH = "requestreply";

    /**
     * Create a request for the method "updateRequestReply".
     *
     * This request holds the parameters needed by the the requestreplyendpoint server.  After setting
     * any optional parameters, call the {@link UpdateRequestReply#execute()} method to invoke the
     * remote operation. <p> {@link UpdateRequestReply#initialize(com.google.api.client.googleapis.ser
     * vices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply}
     * @since 1.13
     */
    protected UpdateRequestReply(edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply content) {
      super(Requestreplyendpoint.this, "PUT", REST_PATH, content, edu.columbia.cloud.plnr.entities.requestreplyendpoint.model.RequestReply.class);
    }

    @Override
    public UpdateRequestReply setAlt(java.lang.String alt) {
      return (UpdateRequestReply) super.setAlt(alt);
    }

    @Override
    public UpdateRequestReply setFields(java.lang.String fields) {
      return (UpdateRequestReply) super.setFields(fields);
    }

    @Override
    public UpdateRequestReply setKey(java.lang.String key) {
      return (UpdateRequestReply) super.setKey(key);
    }

    @Override
    public UpdateRequestReply setOauthToken(java.lang.String oauthToken) {
      return (UpdateRequestReply) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRequestReply setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRequestReply) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRequestReply setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRequestReply) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRequestReply setUserIp(java.lang.String userIp) {
      return (UpdateRequestReply) super.setUserIp(userIp);
    }

    @Override
    public UpdateRequestReply set(String parameterName, Object value) {
      return (UpdateRequestReply) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Requestreplyendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Requestreplyendpoint}. */
    @Override
    public Requestreplyendpoint build() {
      return new Requestreplyendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RequestreplyendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRequestreplyendpointRequestInitializer(
        RequestreplyendpointRequestInitializer requestreplyendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(requestreplyendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
