/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-08 at 00:40:24 UTC 
 * Modify at your own risk.
 */

package edu.columbia.cloud.plnr.entities.subjectendpoint;

/**
 * Service definition for Subjectendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link SubjectendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Subjectendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the subjectendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "subjectendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Subjectendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Subjectendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getSubject".
   *
   * This request holds the parameters needed by the the subjectendpoint server.  After setting any
   * optional parameters, call the {@link GetSubject#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetSubject getSubject(java.lang.Long id) throws java.io.IOException {
    GetSubject result = new GetSubject(id);
    initialize(result);
    return result;
  }

  public class GetSubject extends SubjectendpointRequest<edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject> {

    private static final String REST_PATH = "subject/{id}";

    /**
     * Create a request for the method "getSubject".
     *
     * This request holds the parameters needed by the the subjectendpoint server.  After setting any
     * optional parameters, call the {@link GetSubject#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetSubject#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSubject(java.lang.Long id) {
      super(Subjectendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSubject setAlt(java.lang.String alt) {
      return (GetSubject) super.setAlt(alt);
    }

    @Override
    public GetSubject setFields(java.lang.String fields) {
      return (GetSubject) super.setFields(fields);
    }

    @Override
    public GetSubject setKey(java.lang.String key) {
      return (GetSubject) super.setKey(key);
    }

    @Override
    public GetSubject setOauthToken(java.lang.String oauthToken) {
      return (GetSubject) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSubject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSubject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSubject setQuotaUser(java.lang.String quotaUser) {
      return (GetSubject) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSubject setUserIp(java.lang.String userIp) {
      return (GetSubject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetSubject setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSubject set(String parameterName, Object value) {
      return (GetSubject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertSubject".
   *
   * This request holds the parameters needed by the the subjectendpoint server.  After setting any
   * optional parameters, call the {@link InsertSubject#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject}
   * @return the request
   */
  public InsertSubject insertSubject(edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject content) throws java.io.IOException {
    InsertSubject result = new InsertSubject(content);
    initialize(result);
    return result;
  }

  public class InsertSubject extends SubjectendpointRequest<edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject> {

    private static final String REST_PATH = "subject";

    /**
     * Create a request for the method "insertSubject".
     *
     * This request holds the parameters needed by the the subjectendpoint server.  After setting any
     * optional parameters, call the {@link InsertSubject#execute()} method to invoke the remote
     * operation. <p> {@link InsertSubject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject}
     * @since 1.13
     */
    protected InsertSubject(edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject content) {
      super(Subjectendpoint.this, "POST", REST_PATH, content, edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject.class);
    }

    @Override
    public InsertSubject setAlt(java.lang.String alt) {
      return (InsertSubject) super.setAlt(alt);
    }

    @Override
    public InsertSubject setFields(java.lang.String fields) {
      return (InsertSubject) super.setFields(fields);
    }

    @Override
    public InsertSubject setKey(java.lang.String key) {
      return (InsertSubject) super.setKey(key);
    }

    @Override
    public InsertSubject setOauthToken(java.lang.String oauthToken) {
      return (InsertSubject) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertSubject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertSubject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertSubject setQuotaUser(java.lang.String quotaUser) {
      return (InsertSubject) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertSubject setUserIp(java.lang.String userIp) {
      return (InsertSubject) super.setUserIp(userIp);
    }

    @Override
    public InsertSubject set(String parameterName, Object value) {
      return (InsertSubject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listSubject".
   *
   * This request holds the parameters needed by the the subjectendpoint server.  After setting any
   * optional parameters, call the {@link ListSubject#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListSubject listSubject() throws java.io.IOException {
    ListSubject result = new ListSubject();
    initialize(result);
    return result;
  }

  public class ListSubject extends SubjectendpointRequest<edu.columbia.cloud.plnr.entities.subjectendpoint.model.CollectionResponseSubject> {

    private static final String REST_PATH = "subject";

    /**
     * Create a request for the method "listSubject".
     *
     * This request holds the parameters needed by the the subjectendpoint server.  After setting any
     * optional parameters, call the {@link ListSubject#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListSubject#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListSubject() {
      super(Subjectendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.subjectendpoint.model.CollectionResponseSubject.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListSubject setAlt(java.lang.String alt) {
      return (ListSubject) super.setAlt(alt);
    }

    @Override
    public ListSubject setFields(java.lang.String fields) {
      return (ListSubject) super.setFields(fields);
    }

    @Override
    public ListSubject setKey(java.lang.String key) {
      return (ListSubject) super.setKey(key);
    }

    @Override
    public ListSubject setOauthToken(java.lang.String oauthToken) {
      return (ListSubject) super.setOauthToken(oauthToken);
    }

    @Override
    public ListSubject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListSubject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListSubject setQuotaUser(java.lang.String quotaUser) {
      return (ListSubject) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListSubject setUserIp(java.lang.String userIp) {
      return (ListSubject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListSubject setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListSubject setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListSubject set(String parameterName, Object value) {
      return (ListSubject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeSubject".
   *
   * This request holds the parameters needed by the the subjectendpoint server.  After setting any
   * optional parameters, call the {@link RemoveSubject#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveSubject removeSubject(java.lang.Long id) throws java.io.IOException {
    RemoveSubject result = new RemoveSubject(id);
    initialize(result);
    return result;
  }

  public class RemoveSubject extends SubjectendpointRequest<Void> {

    private static final String REST_PATH = "subject/{id}";

    /**
     * Create a request for the method "removeSubject".
     *
     * This request holds the parameters needed by the the subjectendpoint server.  After setting any
     * optional parameters, call the {@link RemoveSubject#execute()} method to invoke the remote
     * operation. <p> {@link RemoveSubject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveSubject(java.lang.Long id) {
      super(Subjectendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveSubject setAlt(java.lang.String alt) {
      return (RemoveSubject) super.setAlt(alt);
    }

    @Override
    public RemoveSubject setFields(java.lang.String fields) {
      return (RemoveSubject) super.setFields(fields);
    }

    @Override
    public RemoveSubject setKey(java.lang.String key) {
      return (RemoveSubject) super.setKey(key);
    }

    @Override
    public RemoveSubject setOauthToken(java.lang.String oauthToken) {
      return (RemoveSubject) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveSubject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveSubject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveSubject setQuotaUser(java.lang.String quotaUser) {
      return (RemoveSubject) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveSubject setUserIp(java.lang.String userIp) {
      return (RemoveSubject) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveSubject setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveSubject set(String parameterName, Object value) {
      return (RemoveSubject) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateSubject".
   *
   * This request holds the parameters needed by the the subjectendpoint server.  After setting any
   * optional parameters, call the {@link UpdateSubject#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject}
   * @return the request
   */
  public UpdateSubject updateSubject(edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject content) throws java.io.IOException {
    UpdateSubject result = new UpdateSubject(content);
    initialize(result);
    return result;
  }

  public class UpdateSubject extends SubjectendpointRequest<edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject> {

    private static final String REST_PATH = "subject";

    /**
     * Create a request for the method "updateSubject".
     *
     * This request holds the parameters needed by the the subjectendpoint server.  After setting any
     * optional parameters, call the {@link UpdateSubject#execute()} method to invoke the remote
     * operation. <p> {@link UpdateSubject#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject}
     * @since 1.13
     */
    protected UpdateSubject(edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject content) {
      super(Subjectendpoint.this, "PUT", REST_PATH, content, edu.columbia.cloud.plnr.entities.subjectendpoint.model.Subject.class);
    }

    @Override
    public UpdateSubject setAlt(java.lang.String alt) {
      return (UpdateSubject) super.setAlt(alt);
    }

    @Override
    public UpdateSubject setFields(java.lang.String fields) {
      return (UpdateSubject) super.setFields(fields);
    }

    @Override
    public UpdateSubject setKey(java.lang.String key) {
      return (UpdateSubject) super.setKey(key);
    }

    @Override
    public UpdateSubject setOauthToken(java.lang.String oauthToken) {
      return (UpdateSubject) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateSubject setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateSubject) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateSubject setQuotaUser(java.lang.String quotaUser) {
      return (UpdateSubject) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateSubject setUserIp(java.lang.String userIp) {
      return (UpdateSubject) super.setUserIp(userIp);
    }

    @Override
    public UpdateSubject set(String parameterName, Object value) {
      return (UpdateSubject) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Subjectendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Subjectendpoint}. */
    @Override
    public Subjectendpoint build() {
      return new Subjectendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link SubjectendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setSubjectendpointRequestInitializer(
        SubjectendpointRequestInitializer subjectendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(subjectendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
