/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-11-22 19:59:01 UTC)
 * on 2013-12-08 at 00:40:18 UTC 
 * Modify at your own risk.
 */

package edu.columbia.cloud.plnr.entities.requesttojoinendpoint;

/**
 * Service definition for Requesttojoinendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link RequesttojoinendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Requesttojoinendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the requesttojoinendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://myapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "requesttojoinendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Requesttojoinendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Requesttojoinendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getRequestToJoin".
   *
   * This request holds the parameters needed by the the requesttojoinendpoint server.  After setting
   * any optional parameters, call the {@link GetRequestToJoin#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public GetRequestToJoin getRequestToJoin(java.lang.Long id) throws java.io.IOException {
    GetRequestToJoin result = new GetRequestToJoin(id);
    initialize(result);
    return result;
  }

  public class GetRequestToJoin extends RequesttojoinendpointRequest<edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin> {

    private static final String REST_PATH = "requesttojoin/{id}";

    /**
     * Create a request for the method "getRequestToJoin".
     *
     * This request holds the parameters needed by the the requesttojoinendpoint server.  After
     * setting any optional parameters, call the {@link GetRequestToJoin#execute()} method to invoke
     * the remote operation. <p> {@link GetRequestToJoin#initialize(com.google.api.client.googleapis.s
     * ervices.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetRequestToJoin(java.lang.Long id) {
      super(Requesttojoinendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetRequestToJoin setAlt(java.lang.String alt) {
      return (GetRequestToJoin) super.setAlt(alt);
    }

    @Override
    public GetRequestToJoin setFields(java.lang.String fields) {
      return (GetRequestToJoin) super.setFields(fields);
    }

    @Override
    public GetRequestToJoin setKey(java.lang.String key) {
      return (GetRequestToJoin) super.setKey(key);
    }

    @Override
    public GetRequestToJoin setOauthToken(java.lang.String oauthToken) {
      return (GetRequestToJoin) super.setOauthToken(oauthToken);
    }

    @Override
    public GetRequestToJoin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetRequestToJoin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetRequestToJoin setQuotaUser(java.lang.String quotaUser) {
      return (GetRequestToJoin) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetRequestToJoin setUserIp(java.lang.String userIp) {
      return (GetRequestToJoin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetRequestToJoin setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetRequestToJoin set(String parameterName, Object value) {
      return (GetRequestToJoin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertRequestToJoin".
   *
   * This request holds the parameters needed by the the requesttojoinendpoint server.  After setting
   * any optional parameters, call the {@link InsertRequestToJoin#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin}
   * @return the request
   */
  public InsertRequestToJoin insertRequestToJoin(edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin content) throws java.io.IOException {
    InsertRequestToJoin result = new InsertRequestToJoin(content);
    initialize(result);
    return result;
  }

  public class InsertRequestToJoin extends RequesttojoinendpointRequest<edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin> {

    private static final String REST_PATH = "requesttojoin";

    /**
     * Create a request for the method "insertRequestToJoin".
     *
     * This request holds the parameters needed by the the requesttojoinendpoint server.  After
     * setting any optional parameters, call the {@link InsertRequestToJoin#execute()} method to
     * invoke the remote operation. <p> {@link InsertRequestToJoin#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin}
     * @since 1.13
     */
    protected InsertRequestToJoin(edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin content) {
      super(Requesttojoinendpoint.this, "POST", REST_PATH, content, edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin.class);
    }

    @Override
    public InsertRequestToJoin setAlt(java.lang.String alt) {
      return (InsertRequestToJoin) super.setAlt(alt);
    }

    @Override
    public InsertRequestToJoin setFields(java.lang.String fields) {
      return (InsertRequestToJoin) super.setFields(fields);
    }

    @Override
    public InsertRequestToJoin setKey(java.lang.String key) {
      return (InsertRequestToJoin) super.setKey(key);
    }

    @Override
    public InsertRequestToJoin setOauthToken(java.lang.String oauthToken) {
      return (InsertRequestToJoin) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertRequestToJoin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertRequestToJoin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertRequestToJoin setQuotaUser(java.lang.String quotaUser) {
      return (InsertRequestToJoin) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertRequestToJoin setUserIp(java.lang.String userIp) {
      return (InsertRequestToJoin) super.setUserIp(userIp);
    }

    @Override
    public InsertRequestToJoin set(String parameterName, Object value) {
      return (InsertRequestToJoin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listRequestToJoin".
   *
   * This request holds the parameters needed by the the requesttojoinendpoint server.  After setting
   * any optional parameters, call the {@link ListRequestToJoin#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListRequestToJoin listRequestToJoin() throws java.io.IOException {
    ListRequestToJoin result = new ListRequestToJoin();
    initialize(result);
    return result;
  }

  public class ListRequestToJoin extends RequesttojoinendpointRequest<edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.CollectionResponseRequestToJoin> {

    private static final String REST_PATH = "requesttojoin";

    /**
     * Create a request for the method "listRequestToJoin".
     *
     * This request holds the parameters needed by the the requesttojoinendpoint server.  After
     * setting any optional parameters, call the {@link ListRequestToJoin#execute()} method to invoke
     * the remote operation. <p> {@link ListRequestToJoin#initialize(com.google.api.client.googleapis.
     * services.AbstractGoogleClientRequest)} must be called to initialize this instance immediately
     * after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListRequestToJoin() {
      super(Requesttojoinendpoint.this, "GET", REST_PATH, null, edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.CollectionResponseRequestToJoin.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListRequestToJoin setAlt(java.lang.String alt) {
      return (ListRequestToJoin) super.setAlt(alt);
    }

    @Override
    public ListRequestToJoin setFields(java.lang.String fields) {
      return (ListRequestToJoin) super.setFields(fields);
    }

    @Override
    public ListRequestToJoin setKey(java.lang.String key) {
      return (ListRequestToJoin) super.setKey(key);
    }

    @Override
    public ListRequestToJoin setOauthToken(java.lang.String oauthToken) {
      return (ListRequestToJoin) super.setOauthToken(oauthToken);
    }

    @Override
    public ListRequestToJoin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListRequestToJoin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListRequestToJoin setQuotaUser(java.lang.String quotaUser) {
      return (ListRequestToJoin) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListRequestToJoin setUserIp(java.lang.String userIp) {
      return (ListRequestToJoin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListRequestToJoin setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListRequestToJoin setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListRequestToJoin set(String parameterName, Object value) {
      return (ListRequestToJoin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeRequestToJoin".
   *
   * This request holds the parameters needed by the the requesttojoinendpoint server.  After setting
   * any optional parameters, call the {@link RemoveRequestToJoin#execute()} method to invoke the
   * remote operation.
   *
   * @param id
   * @return the request
   */
  public RemoveRequestToJoin removeRequestToJoin(java.lang.Long id) throws java.io.IOException {
    RemoveRequestToJoin result = new RemoveRequestToJoin(id);
    initialize(result);
    return result;
  }

  public class RemoveRequestToJoin extends RequesttojoinendpointRequest<Void> {

    private static final String REST_PATH = "requesttojoin/{id}";

    /**
     * Create a request for the method "removeRequestToJoin".
     *
     * This request holds the parameters needed by the the requesttojoinendpoint server.  After
     * setting any optional parameters, call the {@link RemoveRequestToJoin#execute()} method to
     * invoke the remote operation. <p> {@link RemoveRequestToJoin#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveRequestToJoin(java.lang.Long id) {
      super(Requesttojoinendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveRequestToJoin setAlt(java.lang.String alt) {
      return (RemoveRequestToJoin) super.setAlt(alt);
    }

    @Override
    public RemoveRequestToJoin setFields(java.lang.String fields) {
      return (RemoveRequestToJoin) super.setFields(fields);
    }

    @Override
    public RemoveRequestToJoin setKey(java.lang.String key) {
      return (RemoveRequestToJoin) super.setKey(key);
    }

    @Override
    public RemoveRequestToJoin setOauthToken(java.lang.String oauthToken) {
      return (RemoveRequestToJoin) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveRequestToJoin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveRequestToJoin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveRequestToJoin setQuotaUser(java.lang.String quotaUser) {
      return (RemoveRequestToJoin) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveRequestToJoin setUserIp(java.lang.String userIp) {
      return (RemoveRequestToJoin) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public RemoveRequestToJoin setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveRequestToJoin set(String parameterName, Object value) {
      return (RemoveRequestToJoin) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateRequestToJoin".
   *
   * This request holds the parameters needed by the the requesttojoinendpoint server.  After setting
   * any optional parameters, call the {@link UpdateRequestToJoin#execute()} method to invoke the
   * remote operation.
   *
   * @param content the {@link edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin}
   * @return the request
   */
  public UpdateRequestToJoin updateRequestToJoin(edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin content) throws java.io.IOException {
    UpdateRequestToJoin result = new UpdateRequestToJoin(content);
    initialize(result);
    return result;
  }

  public class UpdateRequestToJoin extends RequesttojoinendpointRequest<edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin> {

    private static final String REST_PATH = "requesttojoin";

    /**
     * Create a request for the method "updateRequestToJoin".
     *
     * This request holds the parameters needed by the the requesttojoinendpoint server.  After
     * setting any optional parameters, call the {@link UpdateRequestToJoin#execute()} method to
     * invoke the remote operation. <p> {@link UpdateRequestToJoin#initialize(com.google.api.client.go
     * ogleapis.services.AbstractGoogleClientRequest)} must be called to initialize this instance
     * immediately after invoking the constructor. </p>
     *
     * @param content the {@link edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin}
     * @since 1.13
     */
    protected UpdateRequestToJoin(edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin content) {
      super(Requesttojoinendpoint.this, "PUT", REST_PATH, content, edu.columbia.cloud.plnr.entities.requesttojoinendpoint.model.RequestToJoin.class);
    }

    @Override
    public UpdateRequestToJoin setAlt(java.lang.String alt) {
      return (UpdateRequestToJoin) super.setAlt(alt);
    }

    @Override
    public UpdateRequestToJoin setFields(java.lang.String fields) {
      return (UpdateRequestToJoin) super.setFields(fields);
    }

    @Override
    public UpdateRequestToJoin setKey(java.lang.String key) {
      return (UpdateRequestToJoin) super.setKey(key);
    }

    @Override
    public UpdateRequestToJoin setOauthToken(java.lang.String oauthToken) {
      return (UpdateRequestToJoin) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateRequestToJoin setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateRequestToJoin) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateRequestToJoin setQuotaUser(java.lang.String quotaUser) {
      return (UpdateRequestToJoin) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateRequestToJoin setUserIp(java.lang.String userIp) {
      return (UpdateRequestToJoin) super.setUserIp(userIp);
    }

    @Override
    public UpdateRequestToJoin set(String parameterName, Object value) {
      return (UpdateRequestToJoin) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Requesttojoinendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Requesttojoinendpoint}. */
    @Override
    public Requesttojoinendpoint build() {
      return new Requesttojoinendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link RequesttojoinendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setRequesttojoinendpointRequestInitializer(
        RequesttojoinendpointRequestInitializer requesttojoinendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(requesttojoinendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
